version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

workflows:
  version: 2
  primary:
    jobs:
      - terraform/fmt:
          context: ftf
          checkout: true
          path: ./infra
      - terraform/validate:
          context: ftf
          checkout: true
          path: ./infra
          requires:
            - terraform/fmt
      - terraform/plan:
          context: ftf
          checkout: true
          path: ./infra
          var: do_token=${DO_TOKEN},env=${CIRCLE_BRANCH}
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          context: ftf
          attach-workspace: true
          path: ./infra
          var: do_token=${DO_TOKEN}
          requires:
            - terraform/plan
          filters:
            branches:
              only: main
