version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

workflows:
  version: 2
  primary:
    jobs:
      - terraform/fmt:
          context: cuffney
          checkout: true
          path: ./infra
      - terraform/validate:
          context: cuffney
          checkout: true
          path: ./infra
          requires:
            - terraform/fmt
      - terraform/plan:
          context: cuffney
          checkout: true
          path: ./infra
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          context: cuffney
          attach-workspace: true
          path: ./infra
          requires:
            - terraform/plan
          filters:
            branches:
              only: main
  # nightly:
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * *" # ~8PM EST.
  #         filters:
  #           branches:
  #             only:
  #               - main
  #   jobs:
  #     - cleanup
